plugins:
  - uses:  
    - plugin: http://localhost:4001
      with:
        labels:
         time:
           - name: "Time: <1 Hour"
           - name: "Time: <2 Hours"
           - name: "Time: <4 Hours"
           - name: "Time: <1 Day"
           - name: "Time: <1 Week"
         priority:
           - name: "Priority: 1 (Normal)"
           - name: "Priority: 2 (Medium)"
           - name: "Priority: 3 (High)"
           - name: "Priority: 4 (Urgent)"
           - name: "Priority: 5 (Emergency)"
  - uses:
    - plugin: http://localhost:4000
      with:
        evmPrivateEncrypted: kmpTKq5Wh9r9x5j3U9GqZr3NYnjK2g0HtbzeUBOuLC2y3x8ja_SKBNlB2AZ6LigXHP_HeMitftVUtzmoj8CFfVP9SqjWoL6IPku1hVTWkdTn97g1IxzmjydFxjdcf0wuDW1hvVtoq3Uw5yALABqxcQ
        incentives:
          contentEvaluator: {}
          userExtractor: {}
          dataPurge: {}
          formattingEvaluator: {}
          permitGeneration: {}
          githubComment: {}
  - uses:
    - plugin: http://localhost:4002
  - uses:
    - plugin: http://localhost:4003
  - uses:
    - plugin: http://localhost:4005
      with:
        model: "gpt-4o-mini"
  - uses:
    - plugin: ubiquity-whilefoo/daemon-disqualifier@development
